### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by ccysfn** [gazeldx/ruby-db-admin#2]
The terminal retured "Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."  when i typed "git clone...<%your project%>"
so ,what should i do next?

**Comment by gazeldx** [comment]
Do not typed "git clone...<%your project%>".

You need copy it and paste.

```
git clone git@github.com:gazeldx/ruby-db-admin.git
```

**Comment by ccysfn** [comment]
thx!
close plz!
